//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transportes_Canas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public int Id { get; set; }
        public int IdWorkTrip { get; set; }
        public int IdDriver { get; set; }
        public int IdAssignmentStatus { get; set; }
        public string TicketNumber { get; set; }
        public int IdTruck { get; set; }
        public int IdTruckBox { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual AssignmentStatu AssignmentStatu { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual WorkTrip WorkTrip { get; set; }
        public virtual Truck Truck { get; set; }
        public virtual TruckBox TruckBox { get; set; }
    }
}
